#ifndef CONFIG_H
#define CONFIG_H

#include <stdint.h>

#define FOSC_HZ 11059200UL

#define CONTROLLER_BAUD 9600UL
#define PRESSURE_BAUD   115200UL

#define SENSOR_TYPE_WIND_PRESSURE 0x02U

#define PRESSURE_MODULE_ADDR 0x01U
#define PRESSURE_POLL_INTERVAL_MS 500U

#define HEARTBEAT_INTERVAL_MS 500U

#endif
